# Generated by Django 3.1 on 2020-08-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=256)),
                ('problem_type', models.CharField(max_length=48)),
                ('metrics_name', models.CharField(max_length=48)),
                ('best_loss', models.FloatField()),
            ],
        ),
    ]
