# Generated by Django 3.1 on 2020-08-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=256)),
                ('column_list', models.TextField()),
                ('column_target', models.CharField(max_length=48)),
                ('eda_path', models.CharField(max_length=128)),
                ('out_path', models.CharField(max_length=128)),
                ('train_results', models.TextField()),
            ],
        ),
    ]
